steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nutripal-e746c/nutripall', '.']
  # Push the container image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nutripal-e746c/nutripall']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
       'beta',
       'run',
       'deploy',
       'nutripall',
       '--image=gcr.io/nutripal-e746c/nutripall',
       '--region',
        'asia-northeast2',
       '--platform',
        'managed',
       '--allow-unauthenticated'
      ]
images:
   'gcr.io/nutripal-e746c/nutripall'